# Generated by Django 4.1.4 on 2023-06-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="userInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=200)),
                ("user_name", models.CharField(max_length=200)),
                (
                    "environment_score",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
