# Generated by Django 4.1.4 on 2023-06-09 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trashCan", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="userNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=200)),
                ("title", models.CharField(max_length=50)),
                ("body", models.CharField(max_length=400)),
            ],
        ),
    ]
